### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by alrusdi** [zenwalker/django-roxyfileman#2]
All functions of roxyfileman is not protected by any rule. With default settings remote user can do everything he wants in MEDIA_ROOT

May be it's better to limit roxyfileman ajax API available only to staff users by default? I have a patch for it if nesesssary

---

Май инглиш сакс поэтому еще по-русски скажу: похоже, что дефолные настройки вьюшек небезопасны. Можно сделать все что угодно в MEDIA_ROOT. Наверное лучше по дефолту давать делать ajax-операции только тем кто может авторизоваться в django-админку? И добавить настройку, которая позволяет задать функцию проверки можно ли данному пользователю выполнять те или иные операции. Готов предложить код для этого.

**Comment by maxpoletaev** [comment]
https://github.com/zenwalker/django-roxyfileman/blob/c7a28e8ff73754172f1485c0d16525491c58b7e6/roxyfileman/urls.py

Сейчас роуты завёрнуты в `staff_member_required`, который делает ровно то, что вы хотите: не даёт пользователю использовать менеджер, если он не админ.

Идея с разделением прав неплохая, добро пожаловать в пулл-реквесты :)
